name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: https://npm.pkg.github.com
      - id: build-and-publish
        shell: bash
        run: |
          npm ci
          npm test
          npm publish
