name: Build and test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm test
